### ISSUE TITLE
How to get BaseAddress ? thanks you

### ISSUE THREAD

**Issue by Exotikcheatt** [kprprivate/EAC-CR3-BYPASS#1]

**Comment by kprprivate** [comment]
#`include <ntifs.h>
#include "defines.h"
#include "getBaseAddress.h"

DWORD64 getProcessBaseAddress(uint32_t src_pid)
{
    PEPROCESS pProcess = NULL;
    if (src_pid == 0) return 0;

    NTSTATUS status = PsLookupProcessByProcessId((HANDLE)src_pid, &pProcess);
    if (!NT_SUCCESS(status)) return 0;

    PVOID Base = 0;

    __try
    {
        Base = PsGetProcessSectionBaseAddress(pProcess);
    }
    __except (EXCEPTION_EXECUTE_HANDLER)
    {
        Base = 0;
    }
    ObDereferenceObject(pProcess);
    return (DWORD64)Base;
`}
